title = "Jonathan Kao"
baseURL = "https://example.com"
theme = "researcher"

[params]
  author = "Jonathan Kao"
  [params.footer]
    text = "By Jonathan Kao"
    url = "https://github.com/jonathankao97"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/jonathankao97"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:jkao97@wharton.upenn.edu"

[permalinks]
  "/" = "/:filename"