title = "Jonathan Kao"
baseURL = "https://jonathankao97.com"
theme = "researcher"

[params]
  author = "Jonathan Kao"
  [params.footer]
    text = "By Jonathan Kao"
    url = "https://github.com/jonathankao97"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/jonathankao97"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:jkao97@wharton.upenn.edu"

[permalinks]
  "/" = "/:filename"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 2
    [[menu.main]]
        name = "My Toolkit"
        url = "/toolkit"
        weight = 3
